Repository Breaking-Dope/breaking-backend, pull requests merged in 2022-08, with the labels that each got.

#165 refactor: add "isfollowing" field to user lists
  src/main/java/com/dope/breaking/api/CommentLikeAPI.java
  src/main/java/com/dope/breaking/api/PostLikeAPI.java
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/domain/user/Follow.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/dto/user/ForListInfoResponseDto.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/service/CommentLikeService.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/main/java/com/dope/breaking/service/PostLikeService.java
  src/test/java/com/dope/breaking/api/CommentLikeAPITest.java
  src/test/java/com/dope/breaking/api/PostLikeAPITest.java
  src/test/java/com/dope/breaking/api/RelationshipAPITest.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
  src/test/java/com/dope/breaking/service/FollowServiceTest.java
  src/test/java/com/dope/breaking/service/PostLikeServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring

#166 feat: refactor JwtAuthenticationFilter Exception
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/test/java/com/dope/breaking/security/jwt/JwtAuthenticationFilterTest.java
Labels: :recycle: Refactoring

#164 fix: change type of isFollowing field to Boolean
  src/main/java/com/dope/breaking/dto/user/ProfileInformationResponseDto.java
Labels: :ambulance: Hot-Fix

#167 feat: add transaction list method
  src/main/java/com/dope/breaking/api/FinancialAPI.java
  src/main/java/com/dope/breaking/domain/financial/Transaction.java
  src/main/java/com/dope/breaking/domain/financial/TransactionType.java
  src/main/java/com/dope/breaking/dto/financial/TransactionResponseDto.java
  src/main/java/com/dope/breaking/exception/bookmark/AlreadyBookmarkedException.java
  src/main/java/com/dope/breaking/repository/TransactionRepository.java
  src/main/java/com/dope/breaking/service/TransactionService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/service/TransactionServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#171 feat: implement logout with redis
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/main/java/com/dope/breaking/service/RedisService.java
  src/test/java/com/dope/breaking/security/jwt/JwtAuthenticationFilterTest.java
Labels: :sparkles: Function, :lock: Security

#173 feat: fix "isAnonymous" annotation not working
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/api/Oauth2LoginAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/auth/AlreadyLoginException.java
  src/test/java/com/dope/breaking/security/controller/Oauth2LoginControllerTest.java
Labels: :bug: Bug

#175 refactor: refactor layer structure of searching feed
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedServiceRepositoryTest.java
Labels: :recycle: Refactoring

#176 feat: implement buyer list feature
  src/main/java/com/dope/breaking/api/FinancialAPI.java
  src/main/java/com/dope/breaking/repository/PurchaseRepository.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/service/PostLikeService.java
  src/main/java/com/dope/breaking/service/PurchaseService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/service/PurchaseServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#187 fix: add isPurchased field on ResponseDto
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :ambulance: Hot-Fix

#182 feat: add post count
  src/main/java/com/dope/breaking/dto/user/ProfileInformationResponseDto.java
  src/main/java/com/dope/breaking/repository/PostRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :sparkles: Function

#180 refactor: refactor location class
  src/main/java/com/dope/breaking/domain/post/Location.java
  src/main/java/com/dope/breaking/dto/post/LocationDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/repository/FeedServiceRepositoryTest.java
  src/test/java/com/dope/breaking/service/PostServiceTest.java
  src/test/java/com/dope/breaking/service/PurchaseServiceTest.java
  src/test/java/com/dope/breaking/service/TransactionServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring

#189 feat: add isLiked and isBookmarked fields for feed
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/repository/BookmarkRepository.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/repository/PostLikeRepository.java
  src/test/java/com/dope/breaking/repository/BookmarkRepositoryTest.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/repository/PostLikeRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#183 fix: unexpected exception there are no comments
  src/main/java/com/dope/breaking/service/CommentService.java
Labels: :ambulance: Hot-Fix

#191 refactor: extend varchar limit for content in database
  src/main/java/com/dope/breaking/domain/post/Post.java
Labels: :recycle: Refactoring

#198 fix: fix setRequestField
  src/main/java/com/dope/breaking/domain/user/User.java
Labels: :ambulance: Hot-Fix

#193 feat: activate user page options
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/exception/user/LoginRequireException.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedServiceRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :recycle: Refactoring

#200 feat: send error log to slack
  build.gradle
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/service/FailableUserInformation.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🧱 Infra

#204 refactor: both upper and lower case letters are requested and returne…
  src/main/java/com/dope/breaking/domain/post/PostType.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :recycle: Refactoring

#206 fix: reply not searched in root comment query
  src/main/java/com/dope/breaking/domain/comment/Comment.java
  src/main/java/com/dope/breaking/repository/CommentRepositoryCustomImpl.java
  src/test/java/com/dope/breaking/repository/CommentRepositoryTest.java
Labels: :ambulance: Hot-Fix

#201 feat: display hidden post when user search my page
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
Labels: :sparkles: Function

#208 fix: unify created time to created-date
  src/main/java/com/dope/breaking/domain/comment/Comment.java
  src/main/java/com/dope/breaking/domain/financial/Transaction.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/comment/CommentResponseDto.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :ambulance: Hot-Fix

#210 feat: distinguish request platform with User-Agent
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/api/Oauth2LoginAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/auth/NotFoundUserAgent.java
  src/main/java/com/dope/breaking/security/jwt/DistinguishUserAgent.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/security/controller/Oauth2LoginControllerTest.java
  src/test/java/com/dope/breaking/security/jwt/JwtAuthenticationFilterTest.java
Labels: :sparkles: Function

#212 feat: add isPurchasable field in post
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/main/java/com/dope/breaking/service/PurchaseService.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/service/PostServiceTest.java
Labels: :sparkles: Function

#214 refactor: update feed field
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/dto/post/LocationDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
Labels: :recycle: Refactoring

#215 feat: hide anonymous post from other user page
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#217 feat: change the key value of the JWT header to lowercase
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :lock: Security

#218 feat: hide anonymous post from other user page
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#220 fix: add condition to feed query for guest
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
Labels: :ambulance: Hot-Fix

#223 feat: unification of date suffixes
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/dto/post/PostRequestDto.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/service/PostServiceTest.java
  src/test/java/com/dope/breaking/service/PurchaseServiceTest.java
  src/test/java/com/dope/breaking/service/TransactionServiceTest.java
Labels: :recycle: Refactoring, :ambulance: Hot-Fix

#226 feat: add pagination for follow&following list
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/dto/user/ForListInfoResponseDto.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/repository/FollowRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/CommentLikeService.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/main/java/com/dope/breaking/service/FollowTargetType.java
  src/main/java/com/dope/breaking/service/PostLikeService.java
  src/main/java/com/dope/breaking/service/PurchaseService.java
  src/test/java/com/dope/breaking/api/RelationshipAPITest.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
  src/test/java/com/dope/breaking/service/FollowServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring, :sparkles: Function

#228 feat: http only cookie to refresh token when Web
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/api/Oauth2LoginAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :recycle: Refactoring

#230 refactor: rename totalCommentCount field
  src/main/java/com/dope/breaking/domain/user/Block.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/exception/CustomInternalErrorException.java
  src/main/java/com/dope/breaking/redis/RedisConfig.java
  src/main/java/com/dope/breaking/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :recycle: Refactoring

#231 feat: implement searching posts by string
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#238 feat: implement searching post by hashtag
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/HashtagService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
Labels: :sparkles: Function

#233 refactor: cursur comment not found exception
  src/main/java/com/dope/breaking/api/CommentAPI.java
  src/main/java/com/dope/breaking/dto/comment/SearchCommentConditionDto.java
  src/main/java/com/dope/breaking/repository/CommentRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/CommentService.java
  src/test/java/com/dope/breaking/repository/CommentRepositoryTest.java
  src/test/java/com/dope/breaking/service/CommentServiceTest.java
Labels: :recycle: Refactoring

#235 refactor: refactor purchase list
  src/main/java/com/dope/breaking/api/FinancialAPI.java
  src/main/java/com/dope/breaking/repository/PurchaseRepository.java
  src/main/java/com/dope/breaking/repository/PurchaseRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/PurchaseRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/PurchaseService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
  src/test/java/com/dope/breaking/repository/PurchaseRepositoryTest.java
  src/test/java/com/dope/breaking/service/PurchaseServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring

#237 feat: post like list pagination
  src/main/java/com/dope/breaking/api/PostLikeAPI.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/pagination/InvalidCursorException.java
  src/main/java/com/dope/breaking/repository/PostLikeRepository.java
  src/main/java/com/dope/breaking/repository/PostLikeRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/PostLikeRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/main/java/com/dope/breaking/service/PostLikeService.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/api/PostLikeAPITest.java
  src/test/java/com/dope/breaking/repository/PostLikeRepositoryTest.java
  src/test/java/com/dope/breaking/service/PostLikeServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring

#240 feat: add Mission entity
  src/main/java/com/dope/breaking/domain/post/Mission.java
  src/main/java/com/dope/breaking/domain/post/Post.java
Labels: :sparkles: Function

#244 feat: implement searching user by string
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/dto/user/SearchUserResponseDto.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/repository/UserRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/UserRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/UserRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#243 feat: add breaking mission creation method
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/dto/mission/MissionRequestDto.java
  src/main/java/com/dope/breaking/dto/post/PostRequestDto.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/post/MissionOnlyForPressException.java
  src/main/java/com/dope/breaking/repository/MissionRepository.java
  src/main/java/com/dope/breaking/service/MissionService.java
  src/test/java/com/dope/breaking/api/MissionAPITest.java
  src/test/java/com/dope/breaking/repository/MissionRepositoryTest.java
  src/test/java/com/dope/breaking/service/MissionServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#246 fix: hot-fix for kakao login bug
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/test/java/com/dope/breaking/security/controller/Oauth2LoginControllerTest.java
Labels: :ambulance: Hot-Fix

#252 feat: implement breaking mission submission
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/domain/post/PostType.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/mission/MissionOnlyForPressException.java
  src/main/java/com/dope/breaking/exception/mission/NoSuchBreakingMissionException.java
  src/main/java/com/dope/breaking/service/MissionService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/MissionAPITest.java
  src/test/java/com/dope/breaking/service/MissionServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#249 refactor: feed query tuning by dynamic join
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/repository/FeedServiceRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :recycle: Refactoring

#257 feat: implement follower count in user search
  src/main/java/com/dope/breaking/dto/user/SearchUserResponseDto.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/repository/UserRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/UserRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#260 fix: dynamic join query bug by outer join
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/repository/FeedServiceRepositoryTest.java
Labels: :ambulance: Hot-Fix

#261 feat: breaking mission detail lookup
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/dto/mission/MissionResponseDto.java
  src/main/java/com/dope/breaking/service/MissionService.java
  src/test/java/com/dope/breaking/api/MissionAPITest.java
  src/test/java/com/dope/breaking/repository/MissionRepositoryTest.java
  src/test/java/com/dope/breaking/service/MissionServiceTest.java
Labels: :sparkles: Function

#265 feat: add pagination to transaction list
  src/main/java/com/dope/breaking/api/FinancialAPI.java
  src/main/java/com/dope/breaking/api/PostLikeAPI.java
  src/main/java/com/dope/breaking/domain/financial/Transaction.java
  src/main/java/com/dope/breaking/dto/financial/TransactionInfoResponseDto.java
  src/main/java/com/dope/breaking/dto/financial/TransactionResponseDto.java
  src/main/java/com/dope/breaking/repository/TransactionRepository.java
  src/main/java/com/dope/breaking/repository/TransactionRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/TransactionRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/PurchaseService.java
  src/main/java/com/dope/breaking/service/TransactionService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/service/PurchaseServiceTest.java
  src/test/java/com/dope/breaking/service/TransactionServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring, :sparkles: Function

#270 fix: fix follow list error when cursor id is zero
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/test/java/com/dope/breaking/api/RelationshipAPITest.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
Labels: :test_tube: Test, :ambulance: Hot-Fix

#268 feat: purchase mission post
  src/main/java/com/dope/breaking/service/PurchaseService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/service/PurchaseServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#271 feat: implement post feed for breaking mission
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/domain/post/PostType.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FeedRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :sparkles: Function

#278 fix: handle RequestRejectedException to response 400 error
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
Labels: :lock: Security

#272 feat: implement watermark on media
  build.gradle
  src/main/java/com/dope/breaking/domain/media/UploadType.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :sparkles: Function

#281 fix: isfollowing bug in searching user
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedServiceTest.java
Labels: :ambulance: Hot-Fix

#275 feat: implement user withdraw
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/repository/BookmarkRepository.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/api/UserAPITest.java
  src/test/java/com/dope/breaking/repository/BookmarkRepositoryTest.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
Labels: :sparkles: Function

#279 feat: implement download media function
  src/main/java/com/dope/breaking/BreakingApplication.java
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/main/resources/application.yml
Labels: :sparkles: Function

#283 fix: change withdraw api method to delete
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/test/java/com/dope/breaking/api/UserAPITest.java
Labels: :ambulance: Hot-Fix

#285 reafactor: controller response type
  src/main/java/com/dope/breaking/api/BookmarkAPI.java
  src/main/java/com/dope/breaking/api/CommentAPI.java
  src/main/java/com/dope/breaking/api/CommentLikeAPI.java
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/api/FinancialAPI.java
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/api/Oauth2LoginAPI.java
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/api/PostLikeAPI.java
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/CommentAPITest.java
  src/test/java/com/dope/breaking/api/CommentLikeAPITest.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/api/PostLikeAPITest.java
  src/test/java/com/dope/breaking/api/RelationshipAPITest.java
Labels: :recycle: Refactoring

#287 fix: add filter to handle RequestRejectedException
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/api/RequestRejectedExceptionHandler.java
Labels: :ambulance: Hot-Fix

#289 fix: hot-fix thumbnail path
  README.md
  src/main/java/com/dope/breaking/service/MediaService.java
Labels: :ambulance: Hot-Fix

#292 fix: add ec2 front url to allowedOrigins for cors policy
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
Labels: :lock: Security, 🧱 Infra

#294 fix: change the encoding type of the string with euc-kr
  src/main/java/com/dope/breaking/service/MediaService.java
Labels: :ambulance: Hot-Fix

#295 fix: modify image-ratio to original-ratio with 400x300
  src/main/java/com/dope/breaking/service/MediaService.java
Labels: :sparkles: Function
