Repository Breaking-Dope/breaking-backend, pull requests merged in 2022-09, with the labels that each got.

#300 chore: set up spring time zone
  src/main/java/com/dope/breaking/BreakingApplication.java
Labels: :bug: Bug

#302 chore: delete the wildcard from the cors setting and specify it
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
Labels: :sparkles: Function

#305 fix: change security options for cors
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
Labels: :bug: Bug

#307 chore: change basic ffmpeg path for linux
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🧱 Infra

#310 feat: update purpose of isPurchasable
  src/main/java/com/dope/breaking/service/PurchaseService.java
Labels: :bug: Bug, :sparkles: Function

#308 feat: delete the HttpOnly-Cookie when logging out
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
Labels: :sparkles: Function, :lock: Security

#311 fix: fix post-media file compression error
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :bug: Bug, :ambulance: Hot-Fix

#314 feat: add view count to breaking mission
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/domain/post/Mission.java
  src/main/java/com/dope/breaking/dto/mission/MissionFeedResponseDto.java
  src/main/java/com/dope/breaking/dto/mission/MissionResponseDto.java
  src/main/java/com/dope/breaking/repository/MissionRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/MissionService.java
  src/test/java/com/dope/breaking/repository/MissionRepositoryTest.java
Labels: :sparkles: Function

#316 fix: watermark Korean encoding problem
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :ambulance: Hot-Fix

#322 refactor: add isHidden field for post feed
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustomImpl.java
Labels: :sparkles: Function

#320 refactor: change deactive-purchase http method to delete
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
Labels: :recycle: Refactoring

#318 feat: add postCount field to mission feed
  src/main/java/com/dope/breaking/domain/post/Mission.java
  src/main/java/com/dope/breaking/dto/mission/MissionFeedResponseDto.java
  src/main/java/com/dope/breaking/repository/MissionRepositoryCustomImpl.java
  src/test/java/com/dope/breaking/repository/MissionRepositoryTest.java
Labels: :sparkles: Function

#324 feat: add role field to result of validate jwt
  src/main/java/com/dope/breaking/dto/user/UserBriefInformationResponseDto.java
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :sparkles: Function

#328 feat: implement mission feed filter
  src/main/java/com/dope/breaking/api/MissionAPI.java
  src/main/java/com/dope/breaking/repository/MissionRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/MissionRepositoryCustomImpl.java
  src/main/java/com/dope/breaking/service/MissionService.java
  src/main/java/com/dope/breaking/service/SearchMissionConditionDto.java
  src/test/java/com/dope/breaking/api/CommentAPITest.java
  src/test/java/com/dope/breaking/api/CommentLikeAPITest.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/api/MissionAPITest.java
  src/test/java/com/dope/breaking/repository/MissionRepositoryTest.java
  src/test/java/com/dope/breaking/service/CommentLikeServiceTest.java
  src/test/java/com/dope/breaking/service/MissionServiceTest.java
Labels: :sparkles: Function

#329 fix: return a compressed profile image when look-up post details
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :recycle: Refactoring, :sparkles: Function

#334 feat: add createdDate field to read mission
  src/main/java/com/dope/breaking/dto/mission/MissionResponseDto.java
  src/main/java/com/dope/breaking/service/MissionService.java
Labels: :sparkles: Function

#332 fix: hide anonymous post from guest user
  src/main/java/com/dope/breaking/service/SearchFeedService.java
Labels: :ambulance: Hot-Fix
