Repository Breaking-Dope/breaking-backend, pull requests merged in 2022-06, with the labels that each got.

#4 feat: Create entities
  src/main/java/com/dope/breaking/domain/comment/Comment.java
  src/main/java/com/dope/breaking/domain/comment/CommentLike.java
  src/main/java/com/dope/breaking/domain/financial/Purchase.java
  src/main/java/com/dope/breaking/domain/financial/Statement.java
  src/main/java/com/dope/breaking/domain/hashtag/CommentHashtag.java
  src/main/java/com/dope/breaking/domain/hashtag/Hashtag.java
  src/main/java/com/dope/breaking/domain/hashtag/PostHashtag.java
  src/main/java/com/dope/breaking/domain/media/Media.java
  src/main/java/com/dope/breaking/domain/media/MediaType.java
  src/main/java/com/dope/breaking/domain/post/Location.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/domain/post/PostLike.java
  src/main/java/com/dope/breaking/domain/post/PostType.java
  src/main/java/com/dope/breaking/domain/user/Block.java
  src/main/java/com/dope/breaking/domain/user/Bookmark.java
  src/main/java/com/dope/breaking/domain/user/Follow.java
  src/main/java/com/dope/breaking/domain/user/User.java
Labels: :sparkles: Function

#9 feat: Create issue and PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  pull_request_template.md
Labels: :scroll: Doc

#12 feat: Create UserRepository & Implement Sign In logics
  build.gradle
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/dto/user/EmailValidateRequestDto.java
  src/main/java/com/dope/breaking/dto/user/MessageResponseDto.java
  src/main/java/com/dope/breaking/dto/user/NicknameValidateRequestDto.java
  src/main/java/com/dope/breaking/dto/user/PhoneNumberValidateRequestDto.java
  src/main/java/com/dope/breaking/dto/user/SignUpDuplicateType.java
  src/main/java/com/dope/breaking/dto/user/SignUpRequestDto.java
  src/main/java/com/dope/breaking/repository/PostRepository.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/api/UserAPITest.java
  src/test/java/com/dope/breaking/repository/UserRepositoryTest.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#14 feat : add spring security with jwt and OAuth Login Controller
  build.gradle
  src/main/java/com/dope/breaking/BreakingApplication.java
  src/main/java/com/dope/breaking/Security/Handler/JwtExceptHandler.java
  src/main/java/com/dope/breaking/Security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/Security/Jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/Security/Jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/Security/SecurityController/Oauth2LoginController.java
  src/main/java/com/dope/breaking/Security/UserDetails/PrincipalDetails.java
  src/main/java/com/dope/breaking/Security/UserDetails/PrincipalDetailsService.java
  src/main/java/com/dope/breaking/Security/UserInfoDto/UserDto.java
  src/main/java/com/dope/breaking/Security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/Security/config/WebSecurityconfig.java
  src/main/java/com/dope/breaking/domain/user/Role.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/main/resources/application.yml
Labels: :sparkles: Function, :lock: Security

#16 feat: Update all the "findBy" methods in UserRepository to UserService
  src/main/java/com/dope/breaking/Security/SecurityController/Oauth2LoginController.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/api/UserAPITest.java
  src/test/java/com/dope/breaking/repository/UserRepositoryTest.java
Labels: :sparkles: Function

#19 feat: add Oauth2loginController exception handler with try-catch statement
  src/main/java/com/dope/breaking/Security/SecurityController/Oauth2LoginController.java
  src/main/java/com/dope/breaking/Security/UserInfoDto/InvalidAccessTokenResponse.java
  src/main/java/com/dope/breaking/Security/UserInfoDto/UserDto.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :bug: Bug, :sparkles: Function
