Repository Breaking-Dope/breaking-backend, pull requests merged in 2022-07, with the labels that each got.

#23 feat: implement "responseMediaFile" method in MediaService
  src/main/java/com/dope/breaking/service/MediaService.java
Labels: :sparkles: Function

#25 Feat: update Sign in process
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/dto/user/SignUpErrorType.java
  src/main/java/com/dope/breaking/dto/user/SignUpRequestDto.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/api/UserAPITest.java
  src/test/java/com/dope/breaking/repository/UserRepositoryTest.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :sparkles: Function

#28 feat: search default feed API
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedRequestDto.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedResponseDto.java
  src/main/java/com/dope/breaking/dto/post/SearchFilterDto.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/main/java/com/dope/breaking/service/SortFilter.java
  src/test/java/com/dope/breaking/repository/PostRepositoryTest.java
  src/test/java/com/dope/breaking/service/FeedSearchServiceTest.java
Labels: :sparkles: Function

#30 feat: add post create function
  .gitignore
  build.gradle
  src/main/java/com/dope/breaking/BreakingApplication.java
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/baseTimeEntity/BaseTimeEntity.java
  src/main/java/com/dope/breaking/domain/media/Media.java
  src/main/java/com/dope/breaking/domain/post/Location.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/domain/post/PostType.java
  src/main/java/com/dope/breaking/dto/post/LocationDto.java
  src/main/java/com/dope/breaking/dto/post/PostCreateRequestDto.java
  src/main/java/com/dope/breaking/dto/post/PostResType.java
  src/main/java/com/dope/breaking/dto/post/PostResponse.java
  src/main/java/com/dope/breaking/dto/response/MessageResponseDto.java
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityconfig.java
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
  src/main/java/com/dope/breaking/security/handler/JwtExceptHandler.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/security/userDetails/PrincipalDetails.java
  src/main/java/com/dope/breaking/security/userDetails/PrincipalDetailsService.java
  src/main/java/com/dope/breaking/security/userInfoDto/InvalidAccessTokenResponse.java
  src/main/java/com/dope/breaking/security/userInfoDto/UserDto.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/main/resources/application.yml
Labels: :recycle: Refactoring, :sparkles: Function

#34 feat: add suffix for identify Oauth2 Account
  src/main/java/com/dope/breaking/security/config/WebSecurityconfig.java
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
  src/main/java/com/dope/breaking/security/handler/JwtExceptHandler.java
Labels: :lock: Security

#35 feat: add 403 status code in entrypoint
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
Labels: :bug: Bug, :sparkles: Function, :lock: Security

#36 feat : add thumbnail image creation function
  build.gradle
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/PostCreateRequestDto.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/main/resources/application.yml
Labels: :sparkles: Function

#43 refactor: rename and add field for searchFeedDto
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedRequestDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/service/MyPagePostOption.java
  src/main/java/com/dope/breaking/service/MyPageSoldOption.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/main/java/com/dope/breaking/service/SortStrategy.java
  src/test/java/com/dope/breaking/service/FeedSearchServiceTest.java
Labels: :recycle: Refactoring

#48 feat: add modify post function
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/PostRequestDto.java
  src/main/java/com/dope/breaking/dto/post/PostResType.java
  src/main/java/com/dope/breaking/dto/post/PostResponse.java
  src/main/java/com/dope/breaking/repository/MediaRepository.java
  src/main/java/com/dope/breaking/repository/PostRepository.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostService.java
Labels: :sparkles: Function, :lock: Security

#49 Feat: implementation of follow/unfollow
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/user/Follow.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/service/FollowServiceTest.java
Labels: :sparkles: Function

#52 feat: implementation custom exception
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/dto/ErrorResponseDto.java
  src/main/java/com/dope/breaking/exception/BreakingException.java
  src/main/java/com/dope/breaking/exception/oauth/InvalidAccessTokenException.java
  src/main/java/com/dope/breaking/exception/post/PostCreateException.java
  src/main/java/com/dope/breaking/exception/user/NoSuchUserException.java
Labels: :sparkles: Function, :exclamation: Important

#55 feat:Issuing jwt tokens after registering as a member
  src/main/java/com/dope/breaking/api/UserAPI.java
Labels: :sparkles: Function, :exclamation: Important, :lock: Security

#56 feat: security test with MockMvc
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/withMockCustomAuthorize/WithMockCustomUser.java
  src/test/java/com/dope/breaking/withMockCustomAuthorize/WithMockCustomUserSecurityContextFactory.java
Labels: :test_tube: Test, :sparkles: Function, :exclamation: Important

#57 feat: implement validate JWT token API for remember-me
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/dto/user/UserBriefInformationResponseDto.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :sparkles: Function, :exclamation: Important

#64 feat: correct the incorrect mapping
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
  src/test/java/com/dope/breaking/security/controller/GoogleDto.java
  src/test/java/com/dope/breaking/security/controller/Oauth2LoginControllerTest.java
Labels: :rotating_light: Emergency, :exclamation: Important, :ambulance: Hot-Fix, :lock: Security

#65 refactor: move user business logic from controller to service
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/dto/user/EmailValidateRequestDto.java
  src/main/java/com/dope/breaking/dto/user/NicknameValidateRequestDto.java
  src/main/java/com/dope/breaking/dto/user/PhoneNumberValidateRequestDto.java
  src/main/java/com/dope/breaking/dto/user/UpdateUserRequestDto.java
  src/main/java/com/dope/breaking/exception/CustomInternalErrorException.java
  src/main/java/com/dope/breaking/exception/auth/DuplicatedInformationException.java
  src/main/java/com/dope/breaking/exception/auth/InvalidAccessTokenException.java
  src/main/java/com/dope/breaking/exception/auth/invalidUserInformationFormatException.java
  src/main/java/com/dope/breaking/service/FailableUserInformation.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/repository/UserRepositoryTest.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :recycle: Refactoring, :exclamation: Important

#67 fix: regular expressions
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :bug: Bug

#69 fix: validate phone number regular expression
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :bug: Bug

#72 feat: exceaption bug fix
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/exception/auth/InvalidAccessTokenFromOauth2Exception.java
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
Labels: :bug: Bug, :recycle: Refactoring, :ambulance: Hot-Fix

#73 feat: implement refresh token for access token
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityconfig.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/security/controller/Oauth2LoginControllerTest.java
  src/test/java/com/dope/breaking/security/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/dope/breaking/security/jwt/TestController.java
Labels: :sparkles: Function, :exclamation: Important, :lock: Security

#75 feat: add the cors setting that belongs to spring security
  src/main/java/com/dope/breaking/security/config/WebSecurityconfig.java
Labels: :sparkles: Function, :exclamation: Important, :ambulance: Hot-Fix, :lock: Security

#76 feat: cors config for spring security
  src/main/java/com/dope/breaking/security/config/WebMvcConfig.java
  src/main/java/com/dope/breaking/security/config/WebSecurityconfig.java
Labels: :ambulance: Hot-Fix

#78 feat: implement service error code
  src/main/java/com/dope/breaking/api/CustomExceptionHandler.java
  src/main/java/com/dope/breaking/dto/ErrorResponseDto.java
  src/main/java/com/dope/breaking/exception/BreakingException.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/auth/DuplicatedInformationException.java
  src/main/java/com/dope/breaking/exception/auth/ExpiredAccessTokenException.java
  src/main/java/com/dope/breaking/exception/auth/ExpiredRefreshTokenException.java
  src/main/java/com/dope/breaking/exception/auth/InvalidAccessTokenException.java
  src/main/java/com/dope/breaking/exception/auth/InvalidAccessTokenFromOauth2Exception.java
  src/main/java/com/dope/breaking/exception/auth/InvalidRefreshTokenException.java
  src/main/java/com/dope/breaking/exception/auth/invalidUserInformationFormatException.java
  src/main/java/com/dope/breaking/exception/post/PostCreateException.java
  src/main/java/com/dope/breaking/exception/user/DuplicatedUserInformationException.java
  src/main/java/com/dope/breaking/exception/user/InvalidUserInformationFormatException.java
  src/main/java/com/dope/breaking/exception/user/NoSuchUserException.java
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
  src/main/java/com/dope/breaking/service/FailableUserInformation.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
Labels: :scroll: Doc, :recycle: Refactoring, :exclamation: Important

#82 feat: implement user page information API
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/dto/user/ProfileInformationResponseDto.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/api/UserAPITest.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :sparkles: Function

#84 feat: add fields for feed API
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/dto/user/UserBriefInformationResponseDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
Labels: :ambulance: Hot-Fix

#86 feat: resolve UserService conflict error
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :ambulance: Hot-Fix

#91 Feat/97 implement media file response api
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/resources/application.yml
Labels: :recycle: Refactoring

#93 fix: response userBasicInfromation from existing user login
  src/main/java/com/dope/breaking/dto/user/UserBriefInformationResponseDto.java
  src/main/java/com/dope/breaking/security/controller/Oauth2LoginController.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
Labels: :ambulance: Hot-Fix, :lock: Security

#95 feat: User Basic Information Response for SingUp
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/dto/user/UserBriefInformationResponseDto.java
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :sparkles: Function

#96 feat: add isfollowing field to user page API
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/dto/user/ProfileInformationResponseDto.java
  src/main/java/com/dope/breaking/repository/FollowRepository.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/repository/FollowRepositoryTest.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :sparkles: Function

#98 feat: add dynamic querydsl filter
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/service/MyPagePostOption.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/main/java/com/dope/breaking/service/SoldOption.java
  src/test/java/com/dope/breaking/service/FeedSearchServiceTest.java
Labels: :recycle: Refactoring, :sparkles: Function

#103 fix: UpdateUserRequestDTO casting error
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :ambulance: Hot-Fix

#101 feat/97 implement post like service
  src/main/java/com/dope/breaking/api/PostLikeAPI.java
  src/main/java/com/dope/breaking/api/RelationshipAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/domain/post/PostLike.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/dto/user/FollowInfoResponseDto.java~53-implement-followingList
  src/main/java/com/dope/breaking/dto/user/FollowInfoResponseDto.java~HEAD
  src/main/java/com/dope/breaking/dto/user/ForListInfoResponseDto.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/like/AlreadyLikedException.java
  src/main/java/com/dope/breaking/exception/like/AlreadyUnlikedException.java
  src/main/java/com/dope/breaking/exception/post/NoSuchPostException.java
  src/main/java/com/dope/breaking/repository/PostLikeRepository.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/main/java/com/dope/breaking/service/PostLikeService.java
  src/test/java/com/dope/breaking/api/PostLikeAPITest.java
  src/test/java/com/dope/breaking/service/FollowServiceTest.java
  src/test/java/com/dope/breaking/service/PostLikeServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#109 Refactor/108 reset bidirectional relationship between post like and post
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/domain/post/PostLike.java
  src/test/java/com/dope/breaking/service/PostLikeServiceTest.java
Labels: :recycle: Refactoring

#110 feat: implement the detail of the post
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/domain/post/Location.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/dto/post/WriterDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
Labels: :sparkles: Function

#120 fix: duplicated information error when update user
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/test/java/com/dope/breaking/service/UserServiceTest.java
Labels: :ambulance: Hot-Fix

#122 fix: fixed a bug where is is-prefix were omitted in response of postRead function
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
Labels: :ambulance: Hot-Fix

#123 feat: implement comment&reply function
  src/main/java/com/dope/breaking/api/CommentAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/comment/Comment.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/comment/NoSuchCommentException.java
  src/main/java/com/dope/breaking/repository/CommentRepository.java
  src/main/java/com/dope/breaking/service/CommentService.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/test/java/com/dope/breaking/api/CommentAPITest.java
  src/test/java/com/dope/breaking/service/CommentServiceTest.java
Labels: :test_tube: Test, :sparkles: Function, :ambulance: Hot-Fix

#130 refactor: change API method to validate jwt
  src/main/java/com/dope/breaking/api/UserAPI.java
Labels: :recycle: Refactoring

#118 feat: implement the ability to store hashtags
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/domain/comment/Comment.java
  src/main/java/com/dope/breaking/domain/hashtag/CommentHashtag.java
  src/main/java/com/dope/breaking/domain/hashtag/Hashtag.java
  src/main/java/com/dope/breaking/domain/hashtag/HashtagType.java
  src/main/java/com/dope/breaking/domain/hashtag/PostCommentHashtag.java
  src/main/java/com/dope/breaking/domain/hashtag/PostHashtag.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/repository/BookmarkRepository.java
  src/main/java/com/dope/breaking/repository/HashtagRepository.java
  src/main/java/com/dope/breaking/repository/PostCommentHashtagRepository.java
  src/main/java/com/dope/breaking/repository/PurchaseRepository.java
  src/main/java/com/dope/breaking/service/HashtagService.java
  src/main/java/com/dope/breaking/service/MediaService.java
  src/main/java/com/dope/breaking/service/PostCommentHashtagService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/repository/HashtagRepositoryTest.java
  src/test/java/com/dope/breaking/repository/PostCommentHashtagRepositoryTest.java
  src/test/java/com/dope/breaking/service/HashtagServiceTest.java
  src/test/java/com/dope/breaking/service/PostCommentHashtagServiceTest.java
Labels: :sparkles: Function

#135 feat: Implement the function to delete posts
  src/main/java/com/dope/breaking/api/PostAPI.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/post/PurchasedPostException.java
  src/main/java/com/dope/breaking/repository/PostRepository.java
  src/main/java/com/dope/breaking/repository/PurchaseRepository.java
  src/main/java/com/dope/breaking/service/PostCommentHashtagService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/service/PostCommentHashtagServiceTest.java
Labels: :sparkles: Function

#136 feat: implement commentLike features
  src/main/java/com/dope/breaking/api/CommentAPI.java
  src/main/java/com/dope/breaking/api/CommentLikeAPI.java
  src/main/java/com/dope/breaking/domain/comment/CommentLike.java
  src/main/java/com/dope/breaking/repository/CommentLikeRepository.java
  src/main/java/com/dope/breaking/service/CommentLikeService.java
  src/test/java/com/dope/breaking/api/CommentLikeAPITest.java
  src/test/java/com/dope/breaking/service/CommentLikeServiceTest.java
  src/test/java/com/dope/breaking/service/CommentServiceTest.java
Labels: :test_tube: Test, :sparkles: Function

#142 feat: update profileImg adjustment logic
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/dto/user/UpdateUserRequestDto.java
  src/main/java/com/dope/breaking/service/UserService.java
Labels: :recycle: Refactoring, :sparkles: Function

#145 feat: implement comment like list feature
  src/main/java/com/dope/breaking/api/CommentLikeAPI.java
  src/main/java/com/dope/breaking/service/CommentLikeService.java
  src/main/java/com/dope/breaking/service/FollowService.java
  src/test/java/com/dope/breaking/api/CommentLikeAPITest.java
Labels: :recycle: Refactoring, :sparkles: Function

#146 feat: refactor PostAPI and PostService test code and add TotalCommentCount and isPurchased field in Post-lookup
  src/main/java/com/dope/breaking/domain/financial/Purchase.java
  src/main/java/com/dope/breaking/dto/post/DetailPostResponseDto.java
  src/main/java/com/dope/breaking/repository/CommentRepository.java
  src/main/java/com/dope/breaking/repository/PurchaseRepository.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/service/PostServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring, :sparkles: Function

#143 refactor: change pagination strategy to cursor based
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/dto/post/FeedResultPostDto.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryCustom.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/service/SearchFeedService.java
  src/test/java/com/dope/breaking/service/FeedSearchServiceTest.java
Labels: :recycle: Refactoring

#147 feat: add hashtag features for comments
  src/main/java/com/dope/breaking/api/CommentAPI.java
  src/main/java/com/dope/breaking/domain/comment/Comment.java
  src/main/java/com/dope/breaking/domain/hashtag/Hashtag.java
  src/main/java/com/dope/breaking/domain/hashtag/PostCommentHashtag.java
  src/main/java/com/dope/breaking/domain/post/Post.java
  src/main/java/com/dope/breaking/dto/comment/CommentRequestDto.java
  src/main/java/com/dope/breaking/repository/HashtagRepository.java
  src/main/java/com/dope/breaking/repository/PostCommentHashtagRepository.java
  src/main/java/com/dope/breaking/service/CommentService.java
  src/main/java/com/dope/breaking/service/HashtagService.java
  src/main/java/com/dope/breaking/service/PostCommentHashtagService.java
  src/main/java/com/dope/breaking/service/PostService.java
  src/test/java/com/dope/breaking/api/CommentAPITest.java
  src/test/java/com/dope/breaking/api/CommentLikeAPITest.java
  src/test/java/com/dope/breaking/api/PostAPITest.java
  src/test/java/com/dope/breaking/repository/HashtagRepositoryTest.java
  src/test/java/com/dope/breaking/repository/PostCommentHashtagRepositoryTest.java
  src/test/java/com/dope/breaking/service/CommentLikeServiceTest.java
  src/test/java/com/dope/breaking/service/CommentServiceTest.java
  src/test/java/com/dope/breaking/service/HashtagServiceTest.java
  src/test/java/com/dope/breaking/service/PostCommentHashtagServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring, :sparkles: Function

#155 feat: implement deposit/withdraw feature
  src/main/java/com/dope/breaking/api/FinancialAPI.java
  src/main/java/com/dope/breaking/domain/financial/Purchase.java
  src/main/java/com/dope/breaking/domain/financial/Statement.java
  src/main/java/com/dope/breaking/domain/financial/Transaction.java
  src/main/java/com/dope/breaking/domain/financial/TransactionType.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/dto/financial/AmountRequestDto.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/financial/NotEnoughBalanceException.java
  src/main/java/com/dope/breaking/repository/StatementRepository.java
  src/main/java/com/dope/breaking/repository/TransactionRepository.java
  src/main/java/com/dope/breaking/service/StatementService.java
  src/main/java/com/dope/breaking/service/TransactionService.java
  src/test/java/com/dope/breaking/api/FinancialAPITest.java
  src/test/java/com/dope/breaking/service/StatementServiceTest.java
Labels: :test_tube: Test, :recycle: Refactoring, :sparkles: Function

#152 feat : implement API for user page feed
  src/main/java/com/dope/breaking/api/FeedAPI.java
  src/main/java/com/dope/breaking/dto/post/SearchFeedConditionDto.java
  src/main/java/com/dope/breaking/repository/FeedRepositoryImpl.java
  src/main/java/com/dope/breaking/service/UserPageFeedOption.java
  src/test/java/com/dope/breaking/service/FeedSearchServiceTest.java
Labels: :sparkles: Function

#154 feat: implement bookmark function
  src/main/java/com/dope/breaking/api/BookmarkAPI.java
  src/main/java/com/dope/breaking/domain/user/Bookmark.java
  src/main/java/com/dope/breaking/exception/ErrorCode.java
  src/main/java/com/dope/breaking/exception/bookmark/AlreadyBookmarkedException.java
  src/main/java/com/dope/breaking/exception/bookmark/AlreadyUnbookmarkedException.java
  src/main/java/com/dope/breaking/repository/BookmarkRepository.java
  src/main/java/com/dope/breaking/service/BookmarkService.java
  src/test/java/com/dope/breaking/api/BookmarkAPITest.java
  src/test/java/com/dope/breaking/service/BookmarkServiceTest.java
Labels: :sparkles: Function

#81 feat: apply Redis and reissue Refresh Token function
  build.gradle
  src/main/java/com/dope/breaking/api/JwtAuthenticationAPI.java
  src/main/java/com/dope/breaking/api/Oauth2LoginAPI.java
  src/main/java/com/dope/breaking/api/UserAPI.java
  src/main/java/com/dope/breaking/domain/user/User.java
  src/main/java/com/dope/breaking/redis/RedisConfig.java
  src/main/java/com/dope/breaking/repository/UserRepository.java
  src/main/java/com/dope/breaking/security/config/WebSecurityConfig.java
  src/main/java/com/dope/breaking/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dope/breaking/security/jwt/JwtEntryPoint.java
  src/main/java/com/dope/breaking/security/jwt/JwtTokenProvider.java
  src/main/java/com/dope/breaking/service/JwtAuthenticationService.java
  src/main/java/com/dope/breaking/service/Oauth2LoginService.java
  src/main/java/com/dope/breaking/service/RedisService.java
  src/main/java/com/dope/breaking/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/dope/breaking/security/jwt/JwtAuthenticationFilterTest.java
  src/test/resources/application.yml
Labels: :recycle: Refactoring, :sparkles: Function, :lock: Security
